# Generated by Django 5.2.9 on 2025-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("done", "Оплачено"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
